version: '3.4'

services:
  sniffer:
    image: sniffer
    build: ./sniffer/
    network_mode: host
  collector_db:
    image: collector_db
    build: ./collector/
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=root
