version: '3.8'

services:
  sniffer:
    image: sniffer
    build: ./sniffer/
    container_name: sniffer
    depends_on:
      - collector_py
    network_mode: host
  collector_py:
    image: collector_py
    build: ./collector/
    container_name: collector_py
    depends_on:
      - collector_mongodb
    ports:
      - "3001:3001/udp"
  collector_mongodb:
    image : mongo
    container_name: collector_mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "3002:27017"
